# .readthedocs.yml

version: 2

# Build settings
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Python dependencies
python:
  install:
    - method: pip
      path: .
    - requirements: docs/source/requirements.txt

# Sphinx configuration
sphinx:
  configuration: docs/source/conf.py

# Build documentation formats
formats:
  - htmlzip
  - pdf
  - epub
